package org.oldskooler.entity4j;

import org.junit.*;
import org.junit.rules.TemporaryFolder;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.oldskooler.entity4j.annotations.Column;
import org.oldskooler.entity4j.annotations.Entity;
import org.oldskooler.entity4j.annotations.Id;
import org.oldskooler.entity4j.annotations.NotMapped;
import org.oldskooler.entity4j.dialect.SqlDialectType;
import org.oldskooler.entity4j.functions.SFunction;
import org.oldskooler.entity4j.mapping.ModelBuilder;

import java.io.File;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.*;

@RunWith(Parameterized.class)
public class CrossDialectIntegrationTest {
    @Parameterized.Parameters(name = "{0}")
    public static Iterable<Object[]> data() {
        return Arrays.asList(new Object[][]{
                {DatabaseFlavor.MYSQL},
                {DatabaseFlavor.POSTGRESQL},
                {DatabaseFlavor.SQLSERVER},
                {DatabaseFlavor.SQLITE}
        });
    }

    @Rule
    public final TemporaryFolder temporaryFolder = new TemporaryFolder();

    private final DatabaseFlavor flavor;
    private Connection connection;
    private TestDbContext context;

    public CrossDialectIntegrationTest(DatabaseFlavor flavor) {
        this.flavor = flavor;
    }

    @Before
    public void setUp() throws Exception {
        connection = flavor.openConnection(temporaryFolder.newFolder(flavor.id));
        context = new TestDbContext(connection, flavor.dialectType);
    }

    @After
    public void tearDown() throws Exception {
        if (context != null) {
            context.close();
        } else if (connection != null && !connection.isClosed()) {
            connection.close();
        }
    }

    @Test
    public void dialectSpecificSqlIsGeneratedCorrectly() {
        String createSql = context.createTableSql(TestUser.class);
        String dropSql = context.dropTableSql(TestUser.class);
        String pagedSql = context.from(TestUser.class)
                .orderBy(o -> o.col(TestUser::getId).asc())
                .offset(2)
                .limit(5)
                .toSql();

        switch (flavor) {
            case MYSQL:
                Assert.assertTrue(createSql.contains("`users`"));
                Assert.assertTrue(createSql.contains("AUTO_INCREMENT"));
                Assert.assertEquals("DROP TABLE IF EXISTS `users`", dropSql);
                Assert.assertTrue(pagedSql.endsWith("LIMIT 5 OFFSET 2"));
                break;
            case POSTGRESQL:
                Assert.assertTrue(createSql.contains("\"users\""));
                Assert.assertTrue(createSql.contains("GENERATED BY DEFAULT AS IDENTITY"));
                Assert.assertEquals("DROP TABLE IF EXISTS \"users\"", dropSql);
                Assert.assertTrue(pagedSql.endsWith("LIMIT 5 OFFSET 2"));
                break;
            case SQLSERVER:
                Assert.assertTrue(createSql.contains("[users]"));
                Assert.assertTrue(createSql.contains("IDENTITY(1,1)"));
                Assert.assertFalse(createSql.contains("IF NOT EXISTS"));
                Assert.assertEquals("DROP TABLE IF EXISTS [users]", dropSql);
                Assert.assertEquals(
                        "SELECT * FROM [users] ORDER BY [id] ASC OFFSET 2 ROWS FETCH NEXT 5 ROWS ONLY",
                        pagedSql
                );
                break;
            case SQLITE:
                Assert.assertTrue(createSql.contains("\"users\""));
                Assert.assertTrue(createSql.contains("INTEGER PRIMARY KEY AUTOINCREMENT"));
                Assert.assertEquals("DROP TABLE IF EXISTS \"users\"", dropSql);
                Assert.assertTrue(pagedSql.endsWith("LIMIT 5 OFFSET 2"));
                break;
            default:
                throw new AssertionError("Unhandled flavor: " + flavor);
        }
    }

    @Test
    public void singleCrudRoundTripPreservesExplicitFalseAndZeroValues() {
        context.createTable(TestUser.class);

        TestUser ada = user("Ada Lovelace", "NEW", false, 0, "4.25", "2024-03-01", "2024-03-01T10:15:30");

        Assert.assertEquals(1, context.insert(ada));
        Assert.assertNotNull(ada.getId());

        TestUser loaded = context.from(TestUser.class)
                .filter(f -> f.equals(TestUser::getName, "Ada Lovelace"))
                .first()
                .orElse(null);

        Assert.assertNotNull(loaded);
        Assert.assertEquals(ada.getId(), loaded.getId());
        Assert.assertEquals("Ada Lovelace", loaded.getName());
        Assert.assertEquals("NEW", loaded.getStatus());
        Assert.assertFalse(Boolean.TRUE.equals(loaded.getActive()));
        Assert.assertEquals(Integer.valueOf(0), loaded.getLoginCount());
        assertBigDecimalEquals("4.25", loaded.getRating());
        Assert.assertEquals(LocalDate.parse("2024-03-01"), loaded.getCreatedOn());
        assertLocalDateTimeEquals(LocalDateTime.parse("2024-03-01T10:15:30"), loaded.getLastSeenAt());

        loaded.setStatus("ACTIVE");
        loaded.setActive(Boolean.TRUE);
        loaded.setLoginCount(1);
        loaded.setRating(new BigDecimal("5.00"));

        Assert.assertEquals(1, context.update(loaded));

        TestUser updated = context.from(TestUser.class)
                .filter(f -> f.equals(TestUser::getId, loaded.getId()))
                .first()
                .orElse(null);

        Assert.assertNotNull(updated);
        Assert.assertEquals("ACTIVE", updated.getStatus());
        Assert.assertTrue(Boolean.TRUE.equals(updated.getActive()));
        Assert.assertEquals(Integer.valueOf(1), updated.getLoginCount());
        assertBigDecimalEquals("5.00", updated.getRating());

        Assert.assertEquals(1, context.delete(updated));
        Assert.assertEquals(0L, context.from(TestUser.class).count());
    }

    @Test
    public void batchCrudOperationsWorkAcrossDialects() {
        context.createTable(TestUser.class);

        List<TestUser> users = Arrays.asList(
                user("Ada", "ACTIVE", true, 1, "3.50", "2024-01-01", "2024-01-01T08:00:00"),
                user("Grace", "ACTIVE", false, 2, "4.10", "2024-01-02", "2024-01-02T09:00:00"),
                user("Linus", "PENDING", true, 3, "4.70", "2024-01-03", "2024-01-03T10:00:00")
        );

        Assert.assertEquals(3, context.insertAll(users));
        for (TestUser user : users) {
            Assert.assertNotNull(user.getId());
        }

        for (TestUser user : users) {
            user.setStatus("SYNCED");
            user.setLoginCount(user.getLoginCount() + 10);
        }

        Assert.assertEquals(3, context.updateAll(users));

        List<TestUser> reloaded = context.from(TestUser.class)
                .orderBy(o -> o.col(TestUser::getId).asc())
                .toList();

        Assert.assertEquals(3, reloaded.size());
        for (TestUser user : reloaded) {
            Assert.assertEquals("SYNCED", user.getStatus());
            Assert.assertTrue(user.getLoginCount() >= 11);
        }

        Assert.assertEquals(2, context.deleteAll(users.subList(0, 2)));
        Assert.assertEquals(1L, context.from(TestUser.class).count());
        Assert.assertEquals("Linus", context.from(TestUser.class).first().get().getName());
    }

    @Test
    public void filteringProjectionJoinAndPaginationScenariosWork() {
        context.createTables(TestUser.class, TestOrder.class);

        TestUser ada = user("Ada", "ACTIVE", true, 1, "4.80", "2024-02-01", "2024-02-01T08:00:00");
        TestUser grace = user("Grace", "ACTIVE", true, 3, "4.20", "2024-02-02", "2024-02-02T09:00:00");
        TestUser linus = user("Linus", "INACTIVE", false, 2, "3.90", "2024-02-03", "2024-02-03T10:00:00");

        context.insert(ada);
        context.insert(grace);
        context.insert(linus);

        context.insert(new TestOrder(null, ada.getId(), new BigDecimal("120.50"), LocalDateTime.parse("2024-02-10T12:00:00")));
        context.insert(new TestOrder(null, ada.getId(), new BigDecimal("80.00"), LocalDateTime.parse("2024-02-11T12:00:00")));
        context.insert(new TestOrder(null, grace.getId(), new BigDecimal("220.00"), LocalDateTime.parse("2024-02-12T12:00:00")));

        long filteredCount = context.from(TestUser.class)
                .filter(f -> f.open()
                        .greaterOrEquals(TestUser::getLoginCount, 1)
                        .and()
                        .like(TestUser::getName, "%a%")
                        .close()
                        .or()
                        .equals(TestUser::getStatus, "INACTIVE"))
                .count();

        Assert.assertEquals(3L, filteredCount);

        Assert.assertEquals(2, context.from(TestUser.class)
                .filter(f -> f.equals(TestUser::getStatus, "ACTIVE"))
                .update(s -> s.set(TestUser::getStatus, "ENABLED")));

        Assert.assertEquals(1, context.from(TestUser.class)
                .filter(f -> f.equals(TestUser::getName, "Ada"))
                .increment(TestUser::getLoginCount, 2));

        Assert.assertEquals(1, context.from(TestUser.class)
                .filter(f -> f.equals(TestUser::getName, "Ada"))
                .decrement(TestUser::getLoginCount, 1));

        TestUser updatedAda = context.from(TestUser.class)
                .filter(f -> f.equals(TestUser::getName, "Ada"))
                .first()
                .orElse(null);

        Assert.assertNotNull(updatedAda);
        Assert.assertEquals(Integer.valueOf(2), updatedAda.getLoginCount());
        Assert.assertEquals("ENABLED", updatedAda.getStatus());

        List<Map<String, Object>> maps = context.from(TestUser.class)
                .select(s -> s
                        .col(TestUser::getId).as("user_id")
                        .col(TestUser::getName).as("name")
                        .col(TestUser::getLoginCount).as("login_count"))
                .filter(f -> f.equalsIgnoreCase(TestUser::getStatus, "enabled"))
                .orderBy(o -> o.col(TestUser::getName).asc())
                .limit(2)
                .toMapList();

        Assert.assertEquals(2, maps.size());
        Assert.assertEquals("Ada", maps.get(0).get("name"));

        List<UserSummary> summaries = context.from(TestUser.class)
                .select(s -> s
                        .col(TestUser::getId).as("user_id")
                        .col(TestUser::getName).as("name")
                        .col(TestUser::getLoginCount).as("login_count"))
                .filter(f -> f.equalsIgnoreCase(TestUser::getStatus, "enabled"))
                .orderBy(o -> o.col(TestUser::getName).asc())
                .toList(UserSummary.class);

        Assert.assertEquals(2, summaries.size());
        Assert.assertEquals("Ada", summaries.get(0).getName());
        Assert.assertEquals(Integer.valueOf(2), summaries.get(0).getLoginCount());

        List<UserOrderRow> rows = context.from(TestUser.class).as("u")
                .innerJoin(TestOrder.class, "o", join ->
                        join.eq(TestUser::getId, TestOrder::getUserId))
                .select(s -> s
                        .col(TestOrder.class, TestOrder::getId).as("order_id")
                        .col(TestUser::getId).as("user_id")
                        .col(TestUser::getName).as("name")
                        .col(TestOrder.class, TestOrder::getTotal).as("total"))
                .filter(f -> f.equals(TestUser::getStatus, "ENABLED")
                        .and()
                        .greater(TestOrder.class, TestOrder::getTotal, new BigDecimal("100.00")))
                .orderBy(o -> o
                        .col(TestUser::getName).asc()
                        .col(TestOrder.class, TestOrder::getPlacedAt).desc())
                .toList(UserOrderRow.class);

        Assert.assertEquals(2, rows.size());
        Assert.assertEquals("Ada", rows.get(0).getName());
        assertBigDecimalEquals("120.50", rows.get(0).getTotal());
        Assert.assertEquals("Grace", rows.get(1).getName());
        assertBigDecimalEquals("220.00", rows.get(1).getTotal());

        List<TestUser> page = context.from(TestUser.class)
                .orderBy(o -> o.col(TestUser::getName).asc())
                .offset(1)
                .limit(1)
                .toList();

        Assert.assertEquals(1, page.size());
        Assert.assertEquals("Grace", page.get(0).getName());
    }

    @Test
    public void complexJoinAggregateAndProjectionScenariosWorkAcrossDialects() {
        context.createTables(TestUser.class, TestOrder.class, TestPayment.class);

        List<TestUser> users = Arrays.asList(
                user("Ada", "ACTIVE", true, 5, "4.50", "2024-05-01", "2024-05-01T08:00:00"),
                user("Grace", "ACTIVE", true, 7, "4.75", "2024-05-02", "2024-05-02T09:00:00"),
                user("Linus", "INACTIVE", false, 1, "3.20", "2024-05-03", "2024-05-03T10:00:00")
        );
        Assert.assertEquals(3, context.insertAll(users));

        List<TestOrder> orders = Arrays.asList(
                new TestOrder(null, users.get(0).getId(), new BigDecimal("120.50"), LocalDateTime.parse("2024-05-10T10:00:00")),
                new TestOrder(null, users.get(0).getId(), new BigDecimal("75.25"), LocalDateTime.parse("2024-05-11T11:00:00")),
                new TestOrder(null, users.get(1).getId(), new BigDecimal("200.00"), LocalDateTime.parse("2024-05-12T12:00:00"))
        );
        Assert.assertEquals(3, context.insertAll(orders));

        List<TestPayment> payments = Arrays.asList(
                new TestPayment(null, users.get(0).getId(), new BigDecimal("120.50"), LocalDateTime.parse("2024-05-13T10:00:00")),
                new TestPayment(null, users.get(1).getId(), new BigDecimal("150.00"), LocalDateTime.parse("2024-05-14T11:00:00")),
                new TestPayment(null, users.get(1).getId(), new BigDecimal("50.00"), LocalDateTime.parse("2024-05-14T12:00:00"))
        );
        Assert.assertEquals(3, context.insertAll(payments));

        List<UserCommerceSummary> summaries = context.from(TestUser.class).as("u")
                .leftJoin(TestOrder.class, "o", join ->
                        join.eq(TestUser::getId, TestOrder::getUserId))
                .leftJoin(TestPayment.class, "p", join ->
                        join.eq(TestUser::getId, TestPayment::getUserId))
                .select(s -> s
                        .col(TestUser::getId).as("user_id")
                        .col(TestUser::getName).as("name")
                        .countDistinct(TestOrder.class, TestOrder::getId).as("order_count")
                        .computed(() -> "COALESCE(SUM(DISTINCT " + s.getColumnName(TestPayment.class, TestPayment::getAmount) + "), 0)").as("payment_total")
                        .max(TestPayment.class, TestPayment::getPaidAt).as("last_paid_at"))
                .groupBy(g -> g
                        .col(TestUser::getId)
                        .col(TestUser::getName))
                .orderBy(o -> o.col(TestUser::getName).asc())
                .toList(UserCommerceSummary.class);

        Assert.assertEquals(3, summaries.size());

        Map<String, UserCommerceSummary> byName = new LinkedHashMap<String, UserCommerceSummary>();
        for (UserCommerceSummary summary : summaries) {
            byName.put(summary.getName(), summary);
        }

        Assert.assertEquals(Long.valueOf(2L), byName.get("Ada").getOrderCount());
        assertBigDecimalEquals("120.50", byName.get("Ada").getPaymentTotal());
        assertLocalDateTimeEquals(LocalDateTime.parse("2024-05-13T10:00:00"), byName.get("Ada").getLastPaidAt());

        Assert.assertEquals(Long.valueOf(1L), byName.get("Grace").getOrderCount());
        assertBigDecimalEquals("200.00", byName.get("Grace").getPaymentTotal());
        assertLocalDateTimeEquals(LocalDateTime.parse("2024-05-14T12:00:00"), byName.get("Grace").getLastPaidAt());

        Assert.assertEquals(Long.valueOf(0L), byName.get("Linus").getOrderCount());
        assertBigDecimalEquals("0.00", byName.get("Linus").getPaymentTotal());
        Assert.assertNull(byName.get("Linus").getLastPaidAt());
    }

    @Test
    public void chunkedInsertAndAdvancedBulkUpdateScenariosWorkAcrossDialects() {
        context.createTable(TestUser.class);

        List<TestUser> users = new ArrayList<TestUser>();
        LocalDate baseDate = LocalDate.parse("2024-06-01");
        LocalDateTime baseTimestamp = LocalDateTime.parse("2024-06-01T08:00:00");

        for (int i = 1; i <= 270; i++) {
            users.add(new TestUser(
                    null,
                    String.format(Locale.ROOT, "Batch User %03d", i),
                    (i % 3 == 0) ? "QUEUED" : "READY",
                    BigDecimal.valueOf((i % 5) + 1L).setScale(2),
                    i % 2 == 0,
                    baseDate.plusDays(i),
                    baseTimestamp.plusHours(i),
                    i
            ));
        }

        Assert.assertEquals(270, context.insertAll(users));
        Assert.assertNotNull(users.get(0).getId());
        Assert.assertNotNull(users.get(users.size() - 1).getId());

        List<String> targetNames = Arrays.asList("Batch User 001", "Batch User 002", "Batch User 004");

        List<TestUser> updatedUsers = context.from(TestUser.class)
                .filter(f -> f.in(TestUser::getName, targetNames))
                .updateReturningList(s -> s
                        .set(TestUser::getStatus, "SYNCED")
                        .set(TestUser::getActive, Boolean.FALSE));

        Assert.assertEquals(3, updatedUsers.size());
        Set<String> updatedNames = new LinkedHashSet<String>();
        for (TestUser updatedUser : updatedUsers) {
            updatedNames.add(updatedUser.getName());
            Assert.assertEquals("SYNCED", updatedUser.getStatus());
            Assert.assertFalse(Boolean.TRUE.equals(updatedUser.getActive()));
        }
        Assert.assertEquals(new LinkedHashSet<String>(targetNames), updatedNames);

        Optional<TestUser> pinned = context.from(TestUser.class)
                .filter(f -> f.equals(TestUser::getId, users.get(9).getId()))
                .updateReturningOptional(s -> s
                        .set(TestUser::getStatus, "PINNED")
                        .set(TestUser::getRating, new BigDecimal("9.99")));

        Assert.assertTrue(pinned.isPresent());
        Assert.assertEquals("PINNED", pinned.get().getStatus());
        assertBigDecimalEquals("9.99", pinned.get().getRating());

        Map<SFunction<TestUser, ?>, Number> increments = new LinkedHashMap<SFunction<TestUser, ?>, Number>();
        increments.put(TestUser::getLoginCount, 5);
        increments.put(TestUser::getRating, new BigDecimal("1.25"));

        Assert.assertEquals(90, context.from(TestUser.class)
                .filter(f -> f.equals(TestUser::getStatus, "QUEUED"))
                .incrementBatch(increments));

        TestUser queuedSample = context.from(TestUser.class)
                .filter(f -> f.equals(TestUser::getName, "Batch User 003"))
                .first()
                .orElse(null);

        Assert.assertNotNull(queuedSample);
        Assert.assertEquals(Integer.valueOf(8), queuedSample.getLoginCount());
        assertBigDecimalEquals("5.25", queuedSample.getRating());

        Assert.assertEquals(3, context.from(TestUser.class)
                .filter(f -> f.in(TestUser::getName, targetNames))
                .delete());

        Assert.assertEquals(267L, context.from(TestUser.class).count());
        Assert.assertFalse(context.from(TestUser.class)
                .filter(f -> f.equals(TestUser::getName, "Batch User 001"))
                .first()
                .isPresent());
    }

    @Test
    public void transactionsCommitAndRollbackAsExpected() throws Exception {
        context.createTable(TestUser.class);

        context.executeInTransaction((IDbContext.VoidTransactionAction) ctx -> {
            ctx.insert(user("Committed", "ACTIVE", true, 5, "9.99", "2024-04-01", "2024-04-01T11:00:00"));
        });

        Assert.assertEquals(1L, context.from(TestUser.class).count());

        try {
            context.executeInTransaction((IDbContext.VoidTransactionAction) ctx -> {
                ctx.insert(user("Rolled Back", "ACTIVE", true, 6, "8.88", "2024-04-02", "2024-04-02T11:00:00"));
                throw new IllegalStateException("boom");
            });
            Assert.fail("Expected the transaction action to fail");
        } catch (IllegalStateException expected) {
            Assert.assertEquals("boom", expected.getMessage());
        }

        Assert.assertEquals(1L, context.from(TestUser.class).count());
        Assert.assertEquals("Committed", context.from(TestUser.class).first().get().getName());
    }

    @Test
    public void compositePrimaryKeyScenariosWorkAcrossDialects() {
        context.createTable(TestMembership.class);

        TestMembership admin = new TestMembership(1L, "ADMINS", 10);
        TestMembership review = new TestMembership(1L, "REVIEWERS", 20);
        TestMembership ops = new TestMembership(2L, "OPS", 30);

        Assert.assertEquals(3, context.insertAll(Arrays.asList(admin, review, ops)));

        TestMembership loaded = context.from(TestMembership.class)
                .filter(f -> f.equals(TestMembership::getUserId, 1L)
                        .and()
                        .equals(TestMembership::getGroupCode, "ADMINS"))
                .first()
                .orElse(null);

        Assert.assertNotNull(loaded);
        Assert.assertEquals(Integer.valueOf(10), loaded.getPoints());

        loaded.setPoints(15);
        Assert.assertEquals(1, context.update(loaded));

        TestMembership updated = context.from(TestMembership.class)
                .filter(f -> f.equals(TestMembership::getUserId, 1L)
                        .and()
                        .equals(TestMembership::getGroupCode, "ADMINS"))
                .first()
                .orElse(null);

        Assert.assertNotNull(updated);
        Assert.assertEquals(Integer.valueOf(15), updated.getPoints());

        Assert.assertEquals(2, context.deleteAll(Arrays.asList(admin, review)));
        Assert.assertEquals(1L, context.from(TestMembership.class).count());
        Assert.assertEquals(1, context.delete(ops));
        Assert.assertEquals(0L, context.from(TestMembership.class).count());
    }

    private static TestUser user(String name,
                                 String status,
                                 boolean active,
                                 int loginCount,
                                 String rating,
                                 String createdOn,
                                 String lastSeenAt) {
        return new TestUser(
                null,
                name,
                status,
                new BigDecimal(rating),
                active,
                LocalDate.parse(createdOn),
                LocalDateTime.parse(lastSeenAt),
                loginCount
        );
    }

    private static void assertBigDecimalEquals(String expected, BigDecimal actual) {
        Assert.assertNotNull(actual);
        Assert.assertEquals(0, new BigDecimal(expected).compareTo(actual));
    }

    private static void assertLocalDateTimeEquals(LocalDateTime expected, LocalDateTime actual) {
        Assert.assertNotNull(actual);
        Assert.assertEquals(
                expected.truncatedTo(ChronoUnit.SECONDS),
                actual.truncatedTo(ChronoUnit.SECONDS)
        );
    }

    private enum DatabaseFlavor {
        MYSQL("mysql", SqlDialectType.MYSQL) {
            @Override
            Connection openConnection(File folder) throws Exception {
                Class.forName("org.h2.Driver");
                return DriverManager.getConnection(h2Url(folder, "MySQL"));
            }

            @Override
            public String toString() {
                return "MySQL";
            }
        },
        POSTGRESQL("postgresql", SqlDialectType.POSTGRESQL) {
            @Override
            Connection openConnection(File folder) throws Exception {
                Class.forName("org.h2.Driver");
                return DriverManager.getConnection(h2Url(folder, "PostgreSQL"));
            }

            @Override
            public String toString() {
                return "PostgreSQL";
            }
        },
        SQLSERVER("sqlserver", SqlDialectType.SQLSERVER) {
            @Override
            Connection openConnection(File folder) throws Exception {
                Class.forName("org.h2.Driver");
                return DriverManager.getConnection(h2Url(folder, "MSSQLServer"));
            }

            @Override
            public String toString() {
                return "SQL Server";
            }
        },
        SQLITE("sqlite", SqlDialectType.SQLITE) {
            @Override
            Connection openConnection(File folder) throws Exception {
                Class.forName("org.sqlite.JDBC");
                return DriverManager.getConnection("jdbc:sqlite:" + new File(folder, "entity4j.db").getAbsolutePath());
            }

            @Override
            public String toString() {
                return "SQLite";
            }
        };

        private final String id;
        private final SqlDialectType dialectType;

        DatabaseFlavor(String id, SqlDialectType dialectType) {
            this.id = id;
            this.dialectType = dialectType;
        }

        abstract Connection openConnection(File folder) throws Exception;

        private static String h2Url(File folder, String mode) {
            String path = new File(folder, "entity4j").getAbsolutePath().replace('\\', '/');
            return "jdbc:h2:file:" + path
                    + ";MODE=" + mode
                    + ";DATABASE_TO_LOWER=TRUE"
                    + ";DB_CLOSE_ON_EXIT=FALSE";
        }
    }

    private static final class TestDbContext extends DbContext {
        TestDbContext(Connection connection, SqlDialectType dialectType) {
            super(connection, dialectType);
        }

        @Override
        public void onModelCreating(ModelBuilder model) {
        }
    }

    @Entity(table = "users")
    public static class TestUser {
        @Id(auto = true)
        private Long id;

        @Column(name = "full_name", nullable = false, length = 100)
        private String name;

        @Column(nullable = false, length = 30)
        private String status;

        @Column(precision = 10, scale = 2, nullable = false)
        private BigDecimal rating;

        @Column(name = "is_active", nullable = false)
        private Boolean active;

        @Column(name = "created_on", nullable = false)
        private LocalDate createdOn;

        @Column(name = "last_seen_at", nullable = false)
        private LocalDateTime lastSeenAt;

        @Column(name = "login_count", nullable = false)
        private Integer loginCount;

        @NotMapped
        private String ignoredDisplayName;

        public TestUser() {
        }

        public TestUser(Long id,
                        String name,
                        String status,
                        BigDecimal rating,
                        Boolean active,
                        LocalDate createdOn,
                        LocalDateTime lastSeenAt,
                        Integer loginCount) {
            this.id = id;
            this.name = name;
            this.status = status;
            this.rating = rating;
            this.active = active;
            this.createdOn = createdOn;
            this.lastSeenAt = lastSeenAt;
            this.loginCount = loginCount;
        }

        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public String getStatus() {
            return status;
        }

        public void setStatus(String status) {
            this.status = status;
        }

        public BigDecimal getRating() {
            return rating;
        }

        public void setRating(BigDecimal rating) {
            this.rating = rating;
        }

        public Boolean getActive() {
            return active;
        }

        public void setActive(Boolean active) {
            this.active = active;
        }

        public LocalDate getCreatedOn() {
            return createdOn;
        }

        public void setCreatedOn(LocalDate createdOn) {
            this.createdOn = createdOn;
        }

        public LocalDateTime getLastSeenAt() {
            return lastSeenAt;
        }

        public void setLastSeenAt(LocalDateTime lastSeenAt) {
            this.lastSeenAt = lastSeenAt;
        }

        public Integer getLoginCount() {
            return loginCount;
        }

        public void setLoginCount(Integer loginCount) {
            this.loginCount = loginCount;
        }
    }

    @Entity(table = "orders")
    public static class TestOrder {
        @Id(auto = true)
        private Long id;

        @Column(name = "user_id", nullable = false)
        private Long userId;

        @Column(name = "total", precision = 10, scale = 2, nullable = false)
        private BigDecimal total;

        @Column(name = "placed_at", nullable = false)
        private LocalDateTime placedAt;

        public TestOrder() {
        }

        public TestOrder(Long id, Long userId, BigDecimal total, LocalDateTime placedAt) {
            this.id = id;
            this.userId = userId;
            this.total = total;
            this.placedAt = placedAt;
        }

        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public Long getUserId() {
            return userId;
        }

        public void setUserId(Long userId) {
            this.userId = userId;
        }

        public BigDecimal getTotal() {
            return total;
        }

        public void setTotal(BigDecimal total) {
            this.total = total;
        }

        public LocalDateTime getPlacedAt() {
            return placedAt;
        }

        public void setPlacedAt(LocalDateTime placedAt) {
            this.placedAt = placedAt;
        }
    }

    @Entity(table = "payments")
    public static class TestPayment {
        @Id(auto = true)
        private Long id;

        @Column(name = "user_id", nullable = false)
        private Long userId;

        @Column(name = "amount", precision = 10, scale = 2, nullable = false)
        private BigDecimal amount;

        @Column(name = "paid_at", nullable = false)
        private LocalDateTime paidAt;

        public TestPayment() {
        }

        public TestPayment(Long id, Long userId, BigDecimal amount, LocalDateTime paidAt) {
            this.id = id;
            this.userId = userId;
            this.amount = amount;
            this.paidAt = paidAt;
        }

        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public Long getUserId() {
            return userId;
        }

        public void setUserId(Long userId) {
            this.userId = userId;
        }

        public BigDecimal getAmount() {
            return amount;
        }

        public void setAmount(BigDecimal amount) {
            this.amount = amount;
        }

        public LocalDateTime getPaidAt() {
            return paidAt;
        }

        public void setPaidAt(LocalDateTime paidAt) {
            this.paidAt = paidAt;
        }
    }

    @Entity(table = "memberships")
    public static class TestMembership {
        @Id(name = "user_id", auto = false)
        private Long userId;

        @Id(name = "group_code", auto = false)
        private String groupCode;

        @Column(nullable = false)
        private Integer points;

        public TestMembership() {
        }

        public TestMembership(Long userId, String groupCode, Integer points) {
            this.userId = userId;
            this.groupCode = groupCode;
            this.points = points;
        }

        public Long getUserId() {
            return userId;
        }

        public void setUserId(Long userId) {
            this.userId = userId;
        }

        public String getGroupCode() {
            return groupCode;
        }

        public void setGroupCode(String groupCode) {
            this.groupCode = groupCode;
        }

        public Integer getPoints() {
            return points;
        }

        public void setPoints(Integer points) {
            this.points = points;
        }
    }

    public static class UserSummary {
        private Long userId;
        private String name;
        private Integer loginCount;

        public UserSummary() {
        }

        public Long getUserId() {
            return userId;
        }

        public void setUserId(Long userId) {
            this.userId = userId;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public Integer getLoginCount() {
            return loginCount;
        }

        public void setLoginCount(Integer loginCount) {
            this.loginCount = loginCount;
        }
    }

    public static class UserOrderRow {
        private Long orderId;
        private Long userId;
        private String name;
        private BigDecimal total;

        public UserOrderRow() {
        }

        public Long getOrderId() {
            return orderId;
        }

        public void setOrderId(Long orderId) {
            this.orderId = orderId;
        }

        public Long getUserId() {
            return userId;
        }

        public void setUserId(Long userId) {
            this.userId = userId;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public BigDecimal getTotal() {
            return total;
        }

        public void setTotal(BigDecimal total) {
            this.total = total;
        }
    }

    public static class UserCommerceSummary {
        private Long userId;
        private String name;
        private Long orderCount;
        private BigDecimal paymentTotal;
        private LocalDateTime lastPaidAt;

        public UserCommerceSummary() {
        }

        public Long getUserId() {
            return userId;
        }

        public void setUserId(Long userId) {
            this.userId = userId;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public Long getOrderCount() {
            return orderCount;
        }

        public void setOrderCount(Long orderCount) {
            this.orderCount = orderCount;
        }

        public BigDecimal getPaymentTotal() {
            return paymentTotal;
        }

        public void setPaymentTotal(BigDecimal paymentTotal) {
            this.paymentTotal = paymentTotal;
        }

        public LocalDateTime getLastPaidAt() {
            return lastPaidAt;
        }

        public void setLastPaidAt(LocalDateTime lastPaidAt) {
            this.lastPaidAt = lastPaidAt;
        }
    }
}
